name: Azkaban
markdown: redcarpet
highlighter: pygments

tagline: "Open-source Workflow Manager"
image: "img/app.png"
repo: "azkaban/azkaban"
docs: "http://azkaban.github.io/azkaban"

exclude: [vendor]
